# Generated by Django 5.1.7 on 2025-07-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sentiment_score', models.FloatField()),
                ('detected_topics', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
